spring:
  application:
    name: discovery-server

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---

spring:
  config:
    activate:
      on-profile: eureka

server:
  port: 8762

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://myhost/8763/eureka/
    instance:
      hostname: localhost

---

spring:
  config:
    activate:
      on-profile: eureka2

server:
  port: 8763

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    instance:
      hostname: myhost